const REPO='https://github.com/Tianchenggg/Awesome-BUPT-International-School-Notes';
const app=document.querySelector('#app');
const categories={Systems:'Systems & Computing',Networks:'Networks & Security',Hardware:'Hardware & Communications',Mathematics:'Mathematics & Signals',Intelligence:'AI & Data',Software:'Software & Programming',Humanities:'General Studies'};
const icons={book:'<svg viewBox="0 0 24 24"><path d="M12 5c-3-2-6-2-9-1v15c3-1 6-1 9 1 3-2 6-2 9-1V4c-3-1-6-1-9 1Zm0 0v15"/></svg>',grid:'<svg viewBox="0 0 24 24"><rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/><rect x="14" y="14" width="7" height="7" rx="1"/></svg>',check:'<svg viewBox="0 0 24 24"><path d="m5 12 4 4L19 6"/></svg>',test:'<svg viewBox="0 0 24 24"><path d="M9 3h6v4H9zM8 5H5v16h14V5h-3M8 12h8M8 16h5"/></svg>',arrow:'<svg viewBox="0 0 24 24"><path d="M4 12h15m-6-6 6 6-6 6"/></svg>',github:'<svg viewBox="0 0 24 24"><path d="M9 19c-4 1-4-2-6-2m12 5v-4c0-1 0-2-1-2 4 0 6-2 6-5 0-2-1-3-2-4 0-1 0-3-1-4-2 0-3 1-4 1h-2C10 3 8 2 6 3 5 4 5 6 5 7c-1 1-2 2-2 4 0 3 2 5 6 5-1 0-1 1-1 2v4"/></svg>'};
const borrowedIcons={book:'moodle-book',test:'moodle-quiz',grid:'fa-solid-graduation-cap',check:'fa-solid-check',bars:'fa-solid-bars',search:'fa-solid-magnifying-glass',arrow:'fa-solid-chevron-right'};
const icon=name=>borrowedIcons[name]?`<span class="icon borrowed" aria-hidden="true" style="--icon-src:url('assets/icons/${borrowedIcons[name]}.svg')"></span>`:`<span class="icon" aria-hidden="true">${icons[name]||icons.book}</span>`;
const esc=s=>String(s??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const plain=s=>s.replace(/[*`$]/g,'');
const sourceUrl=c=>`${REPO}/blob/main/${c.sourceFile.split('/').map(encodeURIComponent).join('/')}`;
let saved={read:{},mastery:{},drafts:{},last:null};let storageAvailable=true;
try{const d=JSON.parse(localStorage.getItem('bupt-study-v1')||'null');if(d&&typeof d==='object'){for(const key of ['read','mastery','drafts'])if(d[key]&&typeof d[key]==='object')saved[key]=d[key];saved.last=d.last}}catch{storageAvailable=false}
function save(){try{localStorage.setItem('bupt-study-v1',JSON.stringify(saved))}catch{storageAvailable=false}}
let categoryFilter='all',courseSort='name',drawerOpen=false;
let catalog=[],course=null,mode='learn',section=null,session=null,revealed=false,finished=false,query='',routeToken=0,mermaidPromise;
const cache=new Map();
const readIds=c=>Array.isArray(saved.read[c.id])?saved.read[c.id]:[];
const masteryCount=c=>c.questions.filter(q=>saved.mastery[q.id]==='mastered').length;
const brand=`<a class="qm-brand" href="#/" aria-label="BUPT International School Notes"><span class="college-logo"><img src="assets/branding/bupt-international-school-transparent.png" alt="BUPT International School" width="408" height="117"></span></a>`;
function sidebar(){return `<nav class="qm-rail" aria-label="Quick navigation"><a href="#/" title="My Modules" aria-label="My Modules" class="${!course?'active':''}">${icon('grid')}</a>${course?`<a href="#/course/${course.id}/learn" title="Module content" aria-label="Module content" class="${mode==='learn'?'active':''}">${icon('book')}</a><a href="#/course/${course.id}/test" title="Self-assessment" aria-label="Self-assessment" class="${mode==='test'?'active':''}">${icon('test')}</a>`:''}<a href="${REPO}" title="GitHub repository" aria-label="GitHub repository" target="_blank" rel="noopener">${icon('github')}</a></nav>`}
function modulePanel(){
 if(!course)return `<aside class="module-panel"><section class="qm-block"><h2>Learning guide <span>Learning guide</span></h2><div class="qm-block-body"><div class="guide-step"><span class="activity-icon book-icon">${icon('book')}</span><div><strong>Read</strong><p>Choose a module and work through its notes, chapter by chapter.</p></div></div><div class="guide-step"><span class="activity-icon quiz-icon">${icon('test')}</span><div><strong>Recall</strong><p>Try answering first, then reveal the reference answer.</p></div></div><div class="guide-step"><span class="activity-icon check-icon">${icon('check')}</span><div><strong>Review</strong><p>Rate your understanding and revisit questions that need practice.</p></div></div></div></section><section class="qm-block"><h2>Study notes <span>Study principles</span></h2><div class="qm-block-body"><ol class="principles"><li>Pay close attention in the final lectures, when key topics are often highlighted.</li><li>Complete every past paper, group the questions by topic, and learn all the answers.</li><li>Reading slides alone is of little use.</li></ol></div></section><p class="community-note">Student-contributed course notes<br>Independent study resource · No sign-in required</p></aside>`;
 const read=readIds(course).length;
 return `<aside class="module-panel"><section class="qm-block"><h2>Module info <span>Module information</span></h2><div class="qm-block-body"><div class="info-label">Learning resources</div><a class="module-resource" href="#/course/${course.id}/learn"><span class="activity-icon book-icon">${icon('book')}</span><span>Course notes<small>${course.chapters.length} chapters · ${read} chapters read</small></span></a><a class="module-resource" href="#/course/${course.id}/test"><span class="activity-icon quiz-icon">${icon('test')}</span><span>Self-assessment<small>${course.questions.length} questions · ${masteryCount(course)} mastered</small></span></a><div class="progress-track"><span style="width:${100*read/course.chapters.length}%"></span></div><div class="module-progress">Reading progress ${Math.round(100*read/course.chapters.length)}%</div></div></section>${mode==='learn'?`<section class="qm-block chapter-block"><h2>Course index <span>Course index</span></h2><nav class="chapters" aria-label="Course index">${course.chapters.map((c,i)=>`<a class="chapter-link ${c.id===section?.id?'selected':''}" href="#/course/${course.id}/learn/${c.id}" ${c.id===section?.id?'aria-current="page"':''}><span class="chapter-number">${readIds(course).includes(c.id)?'✓':''}</span><span>${esc(plain(c.displayTitle||c.title))}</span></a>`).join('')}</nav></section>`:`<section class="qm-block"><h2>Quiz navigation <span>Quiz navigation</span></h2><div class="qm-block-body"><div class="question-nav">${(session?.ids||[]).map((id,i)=>`<button class="question-dot ${session.index===i&&!finished?'current':''} ${saved.mastery[id]||''}" data-action="jump" data-index="${i}" aria-label="Question ${i+1}${saved.mastery[id]==='mastered'?', mastered':saved.mastery[id]==='review'?', review needed':''}">${i+1}</button>`).join('')}</div><div class="question-legend"><span><i class="legend-mastered"></i>Mastered</span><span><i class="legend-review"></i>Review needed</span></div><p class="quiz-panel-hint">Answers are hidden by default. Reveal the answer, then rate your understanding.</p></div></section>`}<p class="community-note">Your progress is saved in this browser<br>Student-contributed · Unofficial</p></aside>`;
}
function shell(content){app.dataset.view=course?mode:'library';app.classList.toggle('drawer-open',drawerOpen);app.innerHTML=`<header class="qm-header"><button class="drawer-toggle" data-action="drawer" aria-label="Open navigation" aria-expanded="${drawerOpen}" aria-controls="course-drawer">${icon('bars')}</button>${brand}<nav class="qm-primary-nav" aria-label="Main navigation"><a href="#/" class="${!course?'active':''}">My Modules </a><a href="${REPO}" target="_blank" rel="noopener">GitHub</a></nav><span class="open-access">Open access </span></header>${sidebar()}<nav id="course-drawer" class="course-drawer" aria-label="Module navigation" ${drawerOpen?'':'hidden'}><div class="drawer-heading">All modules <button data-action="drawer" aria-label="Close navigation">×</button></div>${catalog.map(c=>`<a href="#/course/${c.id}/learn">${c.name}</a>`).join('')}</nav><div class="workspace"><main id="main" tabindex="-1"><div class="breadcrumbs"><a href="#/">Home</a><span>/</span><a href="#/">My Modules</a>${course?`<span>/</span><span>${course.name}</span>`:''}</div><div class="page-grid"><section class="page-content">${content}</section>${course?modulePanel():''}</div><footer><span>BUPT International School Notes · Open course notes</span><span>Progress is stored in this browser${storageAvailable?'':' · Storage is unavailable'}</span><details class="footer-guide"><summary>Study guide</summary><p>Read a chapter, answer the questions from memory, then reveal the reference answers and rate your understanding.</p><ol><li>Pay close attention in the final lectures, when key topics are often highlighted.</li><li>Complete every past paper, group the questions by topic, and learn all the answers.</li><li>Reading slides alone is of little use.</li></ol></details></footer></main></div>`;}

function card(c){
 const read=Math.min(readIds(c).length,c.chapters),percent=c.chapters?Math.round(100*read/c.chapters):0;
 return `<article class="module-row" aria-labelledby="module-${c.id}"><a class="module-thumb pattern-${c.category}" href="#/course/${c.id}/learn" aria-label="Open ${esc(c.name)}"><span>${esc(c.short)}</span></a><div class="module-details"><div class="module-category">${esc(categories[c.category])}</div><h3 id="module-${c.id}"><a href="#/course/${c.id}/learn">${esc(c.name)}</a></h3><div class="module-completion" aria-label="${esc(c.name)}: ${percent}% read"><span>${percent}% complete</span><span class="completion-detail">${read} of ${c.chapters} chapters read</span></div></div><div class="module-shortcuts"><a href="#/course/${c.id}/learn" title="Course notes">${icon('book')}<span>Notes</span></a><a href="#/course/${c.id}/test" title="${c.questions} self-assessment questions">${icon('test')}<span>Practice</span></a></div></article>`;
}
function library(){course=null;document.title='My Modules | BUPT Study';const last=catalog.find(c=>c.id===saved.last?.course);
 shell(`<div class="library-heading"><h1>My Modules</h1></div><section class="overview-panel"><h2>My Modules</h2>${last?`<a class="continue-banner" href="#/course/${last.id}/learn/${esc(saved.last.section)}"><span>${icon('book')} Recently accessed: <strong>${esc(last.name)}</strong></span></a>`:''}<div class="overview-controls"><label class="visually-hidden" for="course-category">Filter by subject</label><select id="course-category"><option value="all">All subjects</option>${Object.entries(categories).map(([key,value])=>`<option value="${key}" ${categoryFilter===key?'selected':''}>${value}</option>`).join('')}</select><label class="search-box">${icon('search')}<input type="search" id="course-search" aria-label="Search courses" placeholder="Search" value="${esc(query)}"></label><label class="visually-hidden" for="course-sort">Sort courses</label><select id="course-sort"><option value="name" ${courseSort==='name'?'selected':''}>Sort by course name</option><option value="progress" ${courseSort==='progress'?'selected':''}>Sort by progress</option></select><span class="list-view-label">List view</span></div><div class="course-list" id="course-grid" aria-label="Course list">${filteredCards()}</div><div class="catalogue-total">${catalog.length} modules available</div></section>`);
}
function filteredCards(){const q=query.trim().toLowerCase();const list=catalog.filter(c=>(categoryFilter==='all'||c.category===categoryFilter)&&`${c.name} ${c.short} ${c.description} ${categories[c.category]}`.toLowerCase().includes(q));list.sort((a,b)=>courseSort==='progress'?(readIds(b).length/b.chapters-readIds(a).length/a.chapters)||a.name.localeCompare(b.name):a.name.localeCompare(b.name));return list.length?list.map(card).join(''):'<div class="empty-state"><h2>No matching modules</h2><p>Try another name or subject.</p></div>'}

function courseHeader(){return `<div class="course-heading"><div><div class="eyebrow">${categories[course.category]} <span> / ${course.short}</span></div><h1>${course.name}</h1><p>${course.description}</p></div><div class="course-total"><span>${course.chapters.length} chapters</span><span>${course.questions.length} questions</span></div></div><nav class="mode-tabs" aria-label="Learning mode"><a href="#/course/${course.id}/learn/${section?.id||course.chapters[0].id}" class="${mode==='learn'?'active':''}" ${mode==='learn'?'aria-current="page"':''}>${icon('book')} Module content </a><a href="#/course/${course.id}/test" class="${mode==='test'?'active':''}" ${mode==='test'?'aria-current="page"':''}>${icon('test')} Self-assessment <span>${course.questions.length}</span></a></nav>`}
async function diagrams(){const nodes=Array.from(document.querySelectorAll('pre.mermaid'));if(!nodes.length)return;
 try{if(!mermaidPromise)mermaidPromise=import('./vendor/mermaid/mermaid.esm.min.mjs').then(({default:m})=>{m.initialize({startOnLoad:false,securityLevel:'strict',theme:'neutral',fontFamily:'sans-serif',suppressErrorRendering:true});return m});const m=await mermaidPromise;
 for(const node of nodes){if(!node.isConnected)continue;try{await m.run({nodes:[node]})}catch{if(node.isConnected)node.innerHTML='<p class="diagram-error">This diagram is unavailable. Please view it in the original notes.</p>';}}
 }catch{for(const node of nodes)if(node.isConnected)node.innerHTML='<p class="diagram-error">This diagram could not load. Refresh to try again.</p>'}
}
function reading(){const i=course.chapters.indexOf(section);const read=readIds(course).includes(section.id);saved.last={course:course.id,section:section.id};save();
 shell(`${courseHeader()}<div class="mobile-chapter"><label for="chapter-select">Select a chapter</label><select id="chapter-select">${course.chapters.map((s,n)=>`<option value="${s.id}" ${s.id===section.id?'selected':''}>${esc(plain(s.displayTitle||s.title))}</option>`).join('')}</select></div><div class="reading-meta"><span>Module content ${i+1} <span class="muted"> / ${course.chapters.length}</span></span><button class="read-toggle ${read?'is-read':''}" data-action="read" aria-pressed="${read}">${icon('check')}${read?'Chapter completed':'Mark as read'}</button></div><article class="reading-card"><h2 class="chapter-title">${esc(plain(section.displayTitle||section.title))}</h2><div class="prose">${section.html}</div></article><div class="reading-bottom"><a class="button secondary ${i===0?'invisible':''}" href="#/course/${course.id}/learn/${course.chapters[Math.max(0,i-1)].id}" ${i===0?'tabindex="-1" aria-hidden="true"':''}>Previous chapter</a><span>${readIds(course).length} / ${course.chapters.length} chapters read</span>${i<course.chapters.length-1?`<a class="button primary" href="#/course/${course.id}/learn/${course.chapters[i+1].id}">Next chapter </a>`:`<a class="button primary" href="#/course/${course.id}/test">Start self-assessment </a>`}</div>`);diagrams();
}
function startSession(filter='all',shuffle=false,chapter=session?.course===course.id?session.chapter:'all'){let ids=course.questions.filter(q=>(chapter==='all'||q.sectionId===chapter)&&(filter==='all'||(filter==='review'?saved.mastery[q.id]==='review':!saved.mastery[q.id]))).map(q=>q.id);if(shuffle)for(let i=ids.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[ids[i],ids[j]]=[ids[j],ids[i]]}session={course:course.id,filter,chapter,ids,index:0};revealed=false;finished=false;}
function currentQuestion(){return course?.questions.find(q=>q.id===session?.ids[session.index])}
function testPage(){
 const q=currentQuestion();const n=session.ids.length;const reviewed=session.ids.filter(id=>saved.mastery[id]).length;
 let body='';
 if(!n){body=`<div class="empty-state test-empty">${icon('check')}<h2>${session.filter==='review'?'No questions to review yet':session.filter==='unanswered'?'You have rated every question':'No questions in this chapter'}</h2><p>${session.filter==='review'?'Reveal an answer and select “Review again” to add a question here.':'Return to all questions to practise again.'}</p><button class="button primary" data-action="all">Practice all questions</button></div>`}
 else if(finished){const mastered=session.ids.filter(id=>saved.mastery[id]==='mastered').length;const review=session.ids.filter(id=>saved.mastery[id]==='review').length;
 body=`<div class="session-summary"><span class="summary-icon">${icon('check')}</span><div class="eyebrow">SESSION COMPLETE</div><h2>Session complete</h2><p>Use your self-assessment to decide what to review next.</p><div class="summary-stats"><div><b>${mastered}</b><span>Mastered</span></div><div><b>${review}</b><span>Review needed</span></div><div><b>${n-mastered-review}</b><span>Not rated</span></div></div><div class="summary-actions"><button class="button primary" data-action="review" ${!review?'disabled':''}>Review these questions</button><button class="button secondary" data-action="all">Start again</button></div><a class="text-link" href="#/course/${course.id}/learn">Return to the notes</a></div>`;
 }else{
 const rating=saved.mastery[q.id];body=`<div class="quiz-progress"><span>Question <strong>${session.index+1}</strong> of ${n}</span><span>${reviewed} rated</span></div><div class="progress-track"><span style="width:${100*reviewed/n}%"></span></div><article class="question-card"><div class="prose question-prompt">${q.promptHtml}</div><label class="answer-label" for="own-answer">Your answer <span>Optional — you can also answer on paper or in your head</span></label><textarea id="own-answer" rows="4" placeholder="Try explaining it in your own words…">${esc(saved.drafts[q.id]||'')}</textarea><div class="reveal-row"><span>${revealed?'Compare the key points, then rate your understanding.':'The answer is hidden. Reveal it when you are ready.'}</span><button class="button ${revealed?'secondary':'primary'}" data-action="reveal" aria-expanded="${revealed}" aria-controls="reference-answer">${revealed?'Hide answer':'Reveal answer'}</button></div>${revealed?`<section id="reference-answer" class="reference-answer"><div class="answer-heading">${icon('book')} Reference answer</div><div class="prose">${q.answerHtml}</div><a class="source-link" href="#/course/${course.id}/learn/${q.sectionId}/${encodeURIComponent(q.sourceAnchor||q.sourceHeading)}">View this topic in the notes</a></section><div class="self-rating"><span>How well did you know this?</span><div><button class="button rating-review ${rating==='review'?'selected':''}" data-action="rate" data-rating="review" aria-pressed="${rating==='review'}">Review again</button><button class="button rating-mastered ${rating==='mastered'?'selected':''}" data-action="rate" data-rating="mastered" aria-pressed="${rating==='mastered'}">${icon('check')} Mastered</button></div></div>`:''}</article><div class="quiz-navigation"><button class="button secondary" data-action="prev" ${session.index===0?'disabled':''}>Previous question</button><span class="rating-status" role="status">${rating==='mastered'?'Marked: mastered':rating==='review'?'Marked: review needed':'Not rated yet'}</span><button class="button primary" data-action="next">${session.index===n-1?'Finish session':'Next question'} </button></div>`;
 }
 shell(`${courseHeader()}<div class="test-toolbar"><div class="chapter-filter"><label for="quiz-chapter">Chapter</label><select id="quiz-chapter" aria-label="Assessment chapter"><option value="all">All chapters (${course.questions.length} questions)</option>${course.chapters.map((ch,i)=>{const n=course.questions.filter(q=>q.sectionId===ch.id).length;return `<option value="${ch.id}" ${session.chapter===ch.id?'selected':''} ${!n?'disabled':''}>${esc(plain(ch.displayTitle||ch.title))} (${n} questions)</option>`}).join('')}</select></div><div><label for="question-filter">Question set</label><select id="question-filter" aria-label="Question set"><option value="all" ${session.filter==='all'?'selected':''}>All questions</option><option value="review" ${session.filter==='review'?'selected':''}>Review needed</option><option value="unanswered" ${session.filter==='unanswered'?'selected':''}>Not rated</option></select></div><button class="text-button" data-action="shuffle">Shuffle</button></div><div class="test-surface">${body}</div>`);diagrams();
}
async function route(){const token=++routeToken;const parts=location.hash.replace(/^#\/?/,'').split('/');
 if(parts[0]!=='course'){library();return}
 const meta=catalog.find(c=>c.id===parts[1]);if(!meta){shell('<div class="empty-state"><h1>No matching modules</h1><a class="button primary" href="#/">Back to My Modules</a></div>');return}
 try{if(!cache.has(meta.id)){app.setAttribute('aria-busy','true');const response=await fetch(`data/${meta.id}.json`);if(!response.ok)throw Error('load');cache.set(meta.id,await response.json())}if(token!==routeToken)return;
 course=cache.get(meta.id);mode=parts[2]==='test'?'test':'learn';section=course.chapters.find(s=>s.id===parts[3])||course.chapters.find(s=>s.id===saved.last?.section&&saved.last?.course===course.id)||course.chapters[0];document.title=`${course.name} · BUPT Study`;
 if(mode==='test'){if(!session||session.course!==course.id||parts[3]==='new')startSession();revealed=false;testPage()}else reading();window.scrollTo({top:0,behavior:'instant'});
 if(mode==='learn'&&parts[4]){const target=plain(decodeURIComponent(parts[4])).replace(/\s+/g,'').toLowerCase();const anchored=/^source-line-\d+$/.test(target)?document.getElementById(target):null;const heading=anchored||Array.from(document.querySelectorAll('.prose h2,.prose h3,.prose h4,.prose h5,.prose h6')).find(el=>plain(el.innerText).replace(/\s+/g,'').toLowerCase()===target);heading?.scrollIntoView({block:'start',behavior:'instant'})}
 }catch{if(token!==routeToken)return;shell(`<div class="empty-state"><h1>This module could not be opened</h1><p>Check your connection and try again.</p><button class="button primary" data-action="retry">Try again</button></div>`)}finally{if(token===routeToken)app.removeAttribute('aria-busy')}
}
app.addEventListener('input',e=>{if(e.target.id==='course-search'){query=e.target.value;document.querySelector('#course-grid').innerHTML=filteredCards()}if(e.target.id==='own-answer'){const q=currentQuestion();if(q){saved.drafts[q.id]=e.target.value;save()}}});
app.addEventListener('change',e=>{if(e.target.id==='course-category'){categoryFilter=e.target.value;document.querySelector('#course-grid').innerHTML=filteredCards();return}if(e.target.id==='course-sort'){courseSort=e.target.value;document.querySelector('#course-grid').innerHTML=filteredCards();return}if(e.target.id==='chapter-select')location.hash=`/course/${course.id}/learn/${e.target.value}`;if(e.target.id==='quiz-chapter'){startSession(session.filter,false,e.target.value);testPage()}if(e.target.id==='question-filter'){startSession(e.target.value);testPage()}});
app.addEventListener('click',async e=>{if(e.target.closest('#course-drawer a')&&window.innerWidth<=900){drawerOpen=false;app.classList.remove('drawer-open');document.querySelector('#course-drawer').hidden=true;document.querySelector('.drawer-toggle').setAttribute('aria-expanded','false')}const button=e.target.closest('[data-action]');if(!button||button.disabled)return;const action=button.dataset.action;
 if(action==='drawer'){const drawer=document.querySelector('#course-drawer');drawerOpen=!drawerOpen;drawer.hidden=!drawerOpen;app.classList.toggle('drawer-open',drawerOpen);document.querySelector('.drawer-toggle').setAttribute('aria-expanded',String(drawerOpen));return}
 if(action==='retry'){await route();return}
 if(action==='read'){const list=readIds(course);saved.read[course.id]=list.includes(section.id)?list.filter(x=>x!==section.id):[...list,section.id];save();reading();return}
 if(action==='reveal'){revealed=!revealed;testPage();document.querySelector('[data-action="reveal"]')?.focus({preventScroll:true});return}
 if(action==='rate'){if(!revealed)return;const q=currentQuestion();saved.mastery[q.id]=button.dataset.rating;save();testPage();document.querySelector(`[data-rating="${button.dataset.rating}"]`)?.focus({preventScroll:true});return}
 if(action==='shuffle'||action==='all'||action==='review'){startSession(action==='all'?'all':action==='review'?'review':session.filter,action==='shuffle');testPage();return}
 if(action==='next'){if(session.index<session.ids.length-1)session.index++;else finished=true;}
 if(action==='prev'){session.index=Math.max(0,session.index-1);finished=false;}
 if(action==='jump'){session.index=Number(button.dataset.index);finished=false;}
 revealed=false;testPage();document.querySelector('.test-surface')?.scrollIntoView({block:'start',behavior:'instant'});
});
document.querySelector('.skip-link').addEventListener('click',e=>{e.preventDefault();document.querySelector('#main')?.focus()});
window.addEventListener('hashchange',route);
window.addEventListener('keydown',e=>{if(e.key==='Escape'){const d=document.querySelector('#course-drawer');if(d){drawerOpen=false;app.classList.remove('drawer-open');d.hidden=true;document.querySelector('.drawer-toggle')?.setAttribute('aria-expanded','false')}}});
async function boot(){try{const response=await fetch('data/index.json');if(!response.ok)throw Error('index');catalog=await response.json();await route();registerTools()}catch{app.innerHTML='<main><div class="empty-state"><h1>The module catalogue could not load</h1><p>Check your connection and refresh the page.</p><button class="button primary" onclick="location.reload()">Refresh</button></div></main>'}}
function registerTools(){const context=document.modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();const tools=[{name:'list_courses',description:'List available BUPT courses with IDs and chapter/question counts.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>catalog.map(({id,name,chapters,questions})=>({id,name,chapters,questions}))},{name:'open_course',description:'Open a course in reading or self-test mode. Self-test answers remain hidden.',inputSchema:{type:'object',properties:{courseId:{type:'string'},mode:{type:'string',enum:['learn','test']}},required:['courseId','mode'],additionalProperties:false},annotations:{readOnlyHint:false},execute:async input=>{if(!input||!catalog.some(c=>c.id===input.courseId)||!['learn','test'].includes(input.mode))throw Error('Invalid course or mode');history.pushState(null,'',`#/course/${input.courseId}/${input.mode}`);await route();return {courseId:course.id,mode,answerVisible:revealed}}}];for(const tool of tools)try{Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{})}catch{}window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true})}
boot();
