const REPO='https://github.com/Tianchenggg/Awesome-BUPT-International-School-Notes';
const app=document.querySelector('#app');
const categories={Systems:'系统与计算',Networks:'网络与安全',Hardware:'硬件与通信',Mathematics:'数学与信号',Intelligence:'智能与数据',Software:'软件与编程',Humanities:'通识课程'};
const icons={book:'<svg viewBox="0 0 24 24"><path d="M12 5c-3-2-6-2-9-1v15c3-1 6-1 9 1 3-2 6-2 9-1V4c-3-1-6-1-9 1Zm0 0v15"/></svg>',grid:'<svg viewBox="0 0 24 24"><rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/><rect x="14" y="14" width="7" height="7" rx="1"/></svg>',check:'<svg viewBox="0 0 24 24"><path d="m5 12 4 4L19 6"/></svg>',test:'<svg viewBox="0 0 24 24"><path d="M9 3h6v4H9zM8 5H5v16h14V5h-3M8 12h8M8 16h5"/></svg>',arrow:'<svg viewBox="0 0 24 24"><path d="M4 12h15m-6-6 6 6-6 6"/></svg>',github:'<svg viewBox="0 0 24 24"><path d="M9 19c-4 1-4-2-6-2m12 5v-4c0-1 0-2-1-2 4 0 6-2 6-5 0-2-1-3-2-4 0-1 0-3-1-4-2 0-3 1-4 1h-2C10 3 8 2 6 3 5 4 5 6 5 7c-1 1-2 2-2 4 0 3 2 5 6 5-1 0-1 1-1 2v4"/></svg>'};
const borrowedIcons={book:'moodle-book',test:'moodle-quiz',grid:'fa-solid-graduation-cap',check:'fa-solid-check',bars:'fa-solid-bars',search:'fa-solid-magnifying-glass',arrow:'fa-solid-chevron-right'};
const icon=name=>borrowedIcons[name]?`<span class="icon borrowed" aria-hidden="true" style="--icon-src:url('assets/icons/${borrowedIcons[name]}.svg')"></span>`:`<span class="icon" aria-hidden="true">${icons[name]||icons.book}</span>`;
const esc=s=>String(s??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const plain=s=>s.replace(/[*`$]/g,'');
const sourceUrl=c=>`${REPO}/blob/main/${c.sourceFile.split('/').map(encodeURIComponent).join('/')}`;
let saved={read:{},mastery:{},drafts:{},last:null};let storageAvailable=true;
try{const d=JSON.parse(localStorage.getItem('bupt-study-v1')||'null');if(d&&typeof d==='object'){for(const key of ['read','mastery','drafts'])if(d[key]&&typeof d[key]==='object')saved[key]=d[key];saved.last=d.last}}catch{storageAvailable=false}
function save(){try{localStorage.setItem('bupt-study-v1',JSON.stringify(saved))}catch{storageAvailable=false}}
let catalog=[],course=null,mode='learn',section=null,session=null,revealed=false,finished=false,query='',routeToken=0,mermaidPromise;
const cache=new Map();
const readIds=c=>Array.isArray(saved.read[c.id])?saved.read[c.id]:[];
const masteryCount=c=>c.questions.filter(q=>saved.mastery[q.id]==='mastered').length;
const brand=`<a class="qm-brand" href="#/" aria-label="BUPT Study 课程目录"><span>BUPT<span class="brand-study">study</span><sup>+</sup></span></a>`;
function sidebar(){return `<nav class="qm-rail" aria-label="快捷导航"><a href="#/" title="My modules · 课程目录" aria-label="课程目录" class="${!course?'active':''}">${icon('grid')}</a>${course?`<a href="#/course/${course.id}/learn" title="Module content · 课程内容" aria-label="课程内容" class="${mode==='learn'?'active':''}">${icon('book')}</a><a href="#/course/${course.id}/test" title="Self-assessment · 课程自测" aria-label="课程自测" class="${mode==='test'?'active':''}">${icon('test')}</a>`:''}<a href="${REPO}" title="GitHub 项目" aria-label="GitHub 项目" target="_blank" rel="noopener">${icon('github')}</a></nav>`}
function modulePanel(){
 if(!course)return `<aside class="module-panel"><section class="qm-block"><h2>Learning guide <span>学习指南</span></h2><div class="qm-block-body"><div class="guide-step"><span class="activity-icon book-icon">${icon('book')}</span><div><strong>Read · 学习</strong><p>选择课程，按章节阅读完整笔记。</p></div></div><div class="guide-step"><span class="activity-icon quiz-icon">${icon('test')}</span><div><strong>Recall · 自测</strong><p>先自己作答，再展开参考答案。</p></div></div><div class="guide-step"><span class="activity-icon check-icon">${icon('check')}</span><div><strong>Review · 巩固</strong><p>标记掌握情况，重练待复习题目。</p></div></div></div></section><section class="qm-block"><h2>Study notes <span>复习原则</span></h2><div class="qm-block-body"><ol class="principles"><li>最后几节课重点听，老师会讲重点。</li><li>把所有往年题写完，按知识点整理，全部背掉。</li><li>看 PPT 基本没用。</li></ol></div></section><p class="community-note">学生整理的开放课程笔记<br>非官方学习站 · 无需登录</p></aside>`;
 const read=readIds(course).length;
 return `<aside class="module-panel"><section class="qm-block"><h2>Module info <span>课程信息</span></h2><div class="qm-block-body"><div class="info-label">Learning resources</div><a class="module-resource" href="#/course/${course.id}/learn"><span class="activity-icon book-icon">${icon('book')}</span><span>课程笔记<small>${course.chapters.length} 个章节 · ${read} 章已读</small></span></a><a class="module-resource" href="#/course/${course.id}/test"><span class="activity-icon quiz-icon">${icon('test')}</span><span>课程自测<small>${course.questions.length} 道题 · ${masteryCount(course)} 道已掌握</small></span></a><div class="progress-track"><span style="width:${100*read/course.chapters.length}%"></span></div><div class="module-progress">阅读进度 ${Math.round(100*read/course.chapters.length)}%</div></div></section>${mode==='learn'?`<section class="qm-block chapter-block"><h2>Course index <span>章节目录</span></h2><nav class="chapters" aria-label="章节目录">${course.chapters.map((c,i)=>`<a class="chapter-link ${c.id===section?.id?'selected':''}" href="#/course/${course.id}/learn/${c.id}" ${c.id===section?.id?'aria-current="page"':''}><span class="chapter-number">${readIds(course).includes(c.id)?'✓':String(i+1).padStart(2,'0')}</span><span>${esc(plain(c.title))}</span></a>`).join('')}</nav></section>`:`<section class="qm-block"><h2>Quiz navigation <span>题目导航</span></h2><div class="qm-block-body"><div class="question-nav">${(session?.ids||[]).map((id,i)=>`<button class="question-dot ${session.index===i&&!finished?'current':''} ${saved.mastery[id]||''}" data-action="jump" data-index="${i}" aria-label="第 ${i+1} 题${saved.mastery[id]==='mastered'?'，已掌握':saved.mastery[id]==='review'?'，待复习':''}">${i+1}</button>`).join('')}</div><div class="question-legend"><span><i class="legend-mastered"></i>已掌握</span><span><i class="legend-review"></i>待复习</span></div><p class="quiz-panel-hint">答案默认隐藏。对照答案后，按自己的掌握情况标记。</p></div></section>`}<p class="community-note">进度保存在当前浏览器<br>学生整理 · 非官方学习站</p></aside>`;
}
function shell(content){app.dataset.view=course?mode:'library';app.innerHTML=`<header class="qm-header"><button class="drawer-toggle" data-action="drawer" aria-label="展开课程导航" aria-expanded="false" aria-controls="course-drawer">${icon('bars')}</button>${brand}<nav class="qm-primary-nav" aria-label="主导航"><a href="#/" class="${!course?'active':''}">My modules <span>我的课程</span></a><a href="${REPO}" target="_blank" rel="noopener">GitHub ↗</a></nav><span class="open-access">Open access <span>公开学习</span></span></header>${sidebar()}<nav id="course-drawer" class="course-drawer" aria-label="快速选课" hidden><div class="drawer-heading">All modules <button data-action="drawer" aria-label="关闭课程导航">×</button></div>${catalog.map(c=>`<a href="#/course/${c.id}/learn">${c.name}</a>`).join('')}</nav><div class="workspace"><main id="main" tabindex="-1"><div class="breadcrumbs"><a href="#/">Home</a><span>/</span><a href="#/">My modules</a>${course?`<span>/</span><span>${course.name}</span>`:''}</div><div class="page-grid"><section class="page-content">${content}</section>${modulePanel()}</div><footer><span>BUPT International School Notes · 学生开放笔记</span><span>进度仅保存在当前浏览器${storageAvailable?'':' · 当前浏览器无法保存进度'}</span></footer></main></div>`;}

function card(c){const read=readIds(c).length;return `<a class="course-card" href="#/course/${c.id}/learn"><div class="card-top"><span class="course-icon tone-${c.category}">${c.short}</span><span class="course-category">${categories[c.category]}</span></div><h3>${c.name}</h3><p>${c.description}</p><div class="card-bottom"><span>${read?`已读 ${read}/${c.chapters} 章`:`${c.chapters} 章 · ${c.questions} 道自测`}</span><span>${read?'继续学习':'开始学习'} ${icon('arrow')}</span></div></a>`}
function library(){course=null;document.title='BUPT Study · 国际学院学习笔记';const last=catalog.find(c=>c.id===saved.last?.course);
 shell(`<div class="library-heading"><div><div class="eyebrow">北京邮电大学国际学院</div><h1>My modules <span class="heading-cn">我的课程</span></h1><p>选择课程，阅读笔记，检验你的掌握情况。</p></div><div class="library-stat"><b>${catalog.length}</b><span>门课程 · 随时开始</span></div></div>${last?`<a class="continue-banner" href="#/course/${last.id}/learn/${esc(saved.last.section)}"><span>${icon('book')} 继续上次学习 <strong>${last.name}</strong></span>${icon('arrow')}</a>`:''}<div class="section-line"><h2>Course overview <span class="small-count">${catalog.length}</span></h2><label class="search-box">${icon('search')}<input type="search" id="course-search" aria-label="搜索课程" placeholder="搜索课程或知识领域" value="${esc(query)}"></label></div><div class="course-grid" id="course-grid">${filteredCards()}</div>`);
}
function filteredCards(){const q=query.trim().toLowerCase();const list=catalog.filter(c=>`${c.name} ${c.short} ${c.description} ${categories[c.category]}`.toLowerCase().includes(q));return list.length?list.map(card).join(''):'<div class="empty-state"><h2>没有找到这门课程</h2><p>试试英文课程名、缩写或中文知识点。</p></div>'}
function courseHeader(){return `<div class="course-heading"><div><div class="eyebrow">${categories[course.category]} <span> / ${course.short}</span></div><h1>${course.name}</h1><p>${course.description}</p></div><div class="course-total"><span>${course.chapters.length} 个章节</span><span>${course.questions.length} 道自测</span></div></div><nav class="mode-tabs" aria-label="学习模式"><a href="#/course/${course.id}/learn/${section?.id||course.chapters[0].id}" class="${mode==='learn'?'active':''}" ${mode==='learn'?'aria-current="page"':''}>${icon('book')} Module content <span class="tab-cn">课程内容</span></a><a href="#/course/${course.id}/test" class="${mode==='test'?'active':''}" ${mode==='test'?'aria-current="page"':''}>${icon('test')} Self-assessment <span class="tab-cn">课程自测</span><span>${course.questions.length}</span></a></nav>`}
async function diagrams(){const nodes=Array.from(document.querySelectorAll('pre.mermaid'));if(!nodes.length)return;
 try{if(!mermaidPromise)mermaidPromise=import('./vendor/mermaid/mermaid.esm.min.mjs').then(({default:m})=>{m.initialize({startOnLoad:false,securityLevel:'strict',theme:'neutral',fontFamily:'sans-serif',suppressErrorRendering:true});return m});const m=await mermaidPromise;
 for(const node of nodes){if(!node.isConnected)continue;try{await m.run({nodes:[node]})}catch{if(node.isConnected)node.innerHTML='<p class="diagram-error">图示暂时无法显示，请在原始笔记中查看。</p>';}}
 }catch{for(const node of nodes)if(node.isConnected)node.innerHTML='<p class="diagram-error">图示加载失败，请刷新页面重试。</p>'}
}
function reading(){const i=course.chapters.indexOf(section);const read=readIds(course).includes(section.id);saved.last={course:course.id,section:section.id};save();
 shell(`${courseHeader()}<div class="mobile-chapter"><label for="chapter-select">选择章节</label><select id="chapter-select">${course.chapters.map((s,n)=>`<option value="${s.id}" ${s.id===section.id?'selected':''}>${n+1}. ${esc(plain(s.title))}</option>`).join('')}</select></div><div class="reading-meta"><span>CHAPTER ${String(i+1).padStart(2,'0')} <span class="muted"> / ${course.chapters.length}</span></span><button class="read-toggle ${read?'is-read':''}" data-action="read" aria-pressed="${read}">${icon('check')}${read?'已读完本章':'标记本章已读'}</button></div><article class="reading-card"><h2 class="chapter-title">${esc(plain(section.title))}</h2><div class="prose">${section.html}</div></article><div class="reading-bottom"><a class="button secondary ${i===0?'invisible':''}" href="#/course/${course.id}/learn/${course.chapters[Math.max(0,i-1)].id}" ${i===0?'tabindex="-1" aria-hidden="true"':''}>← 上一章</a><span>${readIds(course).length} / ${course.chapters.length} 章已读</span>${i<course.chapters.length-1?`<a class="button primary" href="#/course/${course.id}/learn/${course.chapters[i+1].id}">下一章 ${icon('arrow')}</a>`:`<a class="button primary" href="#/course/${course.id}/test">开始课程自测 ${icon('arrow')}</a>`}</div>`);diagrams();
}
function startSession(filter='all',shuffle=false){let ids=course.questions.filter(q=>filter==='all'||(filter==='review'?saved.mastery[q.id]==='review':!saved.mastery[q.id])).map(q=>q.id);if(shuffle)for(let i=ids.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[ids[i],ids[j]]=[ids[j],ids[i]]}session={course:course.id,filter,ids,index:0};revealed=false;finished=false;}
function currentQuestion(){return course?.questions.find(q=>q.id===session?.ids[session.index])}
function testPage(){
 const q=currentQuestion();const n=session.ids.length;const reviewed=session.ids.filter(id=>saved.mastery[id]).length;
 let body='';
 if(!n){body=`<div class="empty-state test-empty">${icon('check')}<h2>${session.filter==='review'?'还没有待复习的题目':session.filter==='unanswered'?'所有题目都已练习过':'本课程暂无自测题'}</h2><p>${session.filter==='review'?'展开答案后选择“再练一次”，题目就会出现在这里。':'可以回到全部题目，再检验一次掌握情况。'}</p><button class="button primary" data-action="all">练习全部题目</button></div>`}
 else if(finished){const mastered=session.ids.filter(id=>saved.mastery[id]==='mastered').length;const review=session.ids.filter(id=>saved.mastery[id]==='review').length;
 body=`<div class="session-summary"><span class="summary-icon">${icon('check')}</span><div class="eyebrow">SESSION COMPLETE</div><h2>这一轮，辛苦了。</h2><p>对照答案后的自评，比单纯读过更有意义。</p><div class="summary-stats"><div><b>${mastered}</b><span>已掌握</span></div><div><b>${review}</b><span>待复习</span></div><div><b>${n-mastered-review}</b><span>未自评</span></div></div><div class="summary-actions"><button class="button primary" data-action="review" ${!review?'disabled':''}>重练待复习题</button><button class="button secondary" data-action="all">再练一轮</button></div><a class="text-link" href="#/course/${course.id}/learn">返回笔记，巩固知识点 →</a></div>`;
 }else{
 const rating=saved.mastery[q.id];body=`<div class="quiz-progress"><span>第 <strong>${session.index+1}</strong> / ${n} 题</span><span>${reviewed} 道已自评</span></div><div class="progress-track"><span style="width:${100*reviewed/n}%"></span></div><article class="question-card"><div class="question-meta"><span>QUESTION ${String(session.index+1).padStart(2,'0')}</span><span class="type-pill">${q.type==='application'?'应用与计算':'概念与理解'}</span></div><div class="prose question-prompt">${q.promptHtml}</div><label class="answer-label" for="own-answer">你的思路 <span>可选，先在脑中或纸上作答也可以</span></label><textarea id="own-answer" rows="4" placeholder="先试着用自己的话回答…">${esc(saved.drafts[q.id]||'')}</textarea><div class="reveal-row"><span>${revealed?'对照关键点，再评价自己的掌握程度。':'答案已隐藏，准备好后再展开。'}</span><button class="button ${revealed?'secondary':'primary'}" data-action="reveal" aria-expanded="${revealed}" aria-controls="reference-answer">${revealed?'收起参考答案':'查看参考答案'} ${revealed?'↑':'↓'}</button></div>${revealed?`<section id="reference-answer" class="reference-answer"><div class="answer-heading">${icon('book')} 参考答案</div><div class="prose">${q.answerHtml}</div><a class="source-link" href="#/course/${course.id}/learn/${q.sectionId}/${encodeURIComponent(q.sourceHeading)}">回到笔记 · ${esc(plain(q.sourceHeading))} ↗</a></section><div class="self-rating"><span>这道题，我…</span><div><button class="button rating-review ${rating==='review'?'selected':''}" data-action="rate" data-rating="review" aria-pressed="${rating==='review'}">↻ 再练一次</button><button class="button rating-mastered ${rating==='mastered'?'selected':''}" data-action="rate" data-rating="mastered" aria-pressed="${rating==='mastered'}">${icon('check')} 已经掌握</button></div></div>`:''}</article><div class="quiz-navigation"><button class="button secondary" data-action="prev" ${session.index===0?'disabled':''}>← 上一题</button><span class="rating-status" role="status">${rating==='mastered'?'已标记：已掌握':rating==='review'?'已标记：待复习':'尚未自评'}</span><button class="button primary" data-action="next">${session.index===n-1?'查看本轮总结':'下一题'} ${icon('arrow')}</button></div>`;
 }
 shell(`${courseHeader()}<div class="test-toolbar"><div><label for="question-filter">练习范围</label><select id="question-filter" aria-label="练习范围"><option value="all" ${session.filter==='all'?'selected':''}>全部题目</option><option value="review" ${session.filter==='review'?'selected':''}>待复习</option><option value="unanswered" ${session.filter==='unanswered'?'selected':''}>未自评</option></select></div><button class="text-button" data-action="shuffle">⇄ 打乱顺序</button></div><div class="test-surface">${body}</div>`);if(revealed)diagrams();
}
async function route(){const token=++routeToken;const parts=location.hash.replace(/^#\/?/,'').split('/');
 if(parts[0]!=='course'){library();return}
 const meta=catalog.find(c=>c.id===parts[1]);if(!meta){shell('<div class="empty-state"><h1>没有找到这门课程</h1><a class="button primary" href="#/">返回课程目录</a></div>');return}
 try{if(!cache.has(meta.id)){app.setAttribute('aria-busy','true');const response=await fetch(`data/${meta.id}.json`);if(!response.ok)throw Error('load');cache.set(meta.id,await response.json())}if(token!==routeToken)return;
 course=cache.get(meta.id);mode=parts[2]==='test'?'test':'learn';section=course.chapters.find(s=>s.id===parts[3])||course.chapters.find(s=>s.id===saved.last?.section&&saved.last?.course===course.id)||course.chapters[0];document.title=`${course.name} · BUPT Study`;
 if(mode==='test'){if(!session||session.course!==course.id||parts[3]==='new')startSession();revealed=false;testPage()}else reading();window.scrollTo({top:0,behavior:'instant'});
 if(mode==='learn'&&parts[4]){const target=plain(decodeURIComponent(parts[4])).replace(/\s+/g,'').toLowerCase();const heading=Array.from(document.querySelectorAll('.prose h2,.prose h3,.prose h4,.prose h5,.prose h6')).find(el=>plain(el.innerText).replace(/\s+/g,'').toLowerCase()===target);heading?.scrollIntoView({block:'start',behavior:'instant'})}
 }catch{if(token!==routeToken)return;shell(`<div class="empty-state"><h1>这门课暂时没有打开</h1><p>请检查网络，然后再试一次。</p><button class="button primary" data-action="retry">重新加载</button></div>`)}finally{if(token===routeToken)app.removeAttribute('aria-busy')}
}
app.addEventListener('input',e=>{if(e.target.id==='course-search'){query=e.target.value;document.querySelector('#course-grid').innerHTML=filteredCards()}if(e.target.id==='own-answer'){const q=currentQuestion();if(q){saved.drafts[q.id]=e.target.value;save()}}});
app.addEventListener('change',e=>{if(e.target.id==='chapter-select')location.hash=`/course/${course.id}/learn/${e.target.value}`;if(e.target.id==='question-filter'){startSession(e.target.value);testPage()}});
app.addEventListener('click',async e=>{const button=e.target.closest('[data-action]');if(!button||button.disabled)return;const action=button.dataset.action;
 if(action==='drawer'){const drawer=document.querySelector('#course-drawer');drawer.hidden=!drawer.hidden;document.querySelector('.drawer-toggle').setAttribute('aria-expanded',String(!drawer.hidden));return}
 if(action==='retry'){await route();return}
 if(action==='read'){const list=readIds(course);saved.read[course.id]=list.includes(section.id)?list.filter(x=>x!==section.id):[...list,section.id];save();reading();return}
 if(action==='reveal'){revealed=!revealed;testPage();document.querySelector('[data-action="reveal"]')?.focus({preventScroll:true});return}
 if(action==='rate'){if(!revealed)return;const q=currentQuestion();saved.mastery[q.id]=button.dataset.rating;save();testPage();document.querySelector(`[data-rating="${button.dataset.rating}"]`)?.focus({preventScroll:true});return}
 if(action==='shuffle'||action==='all'||action==='review'){startSession(action==='all'?'all':action==='review'?'review':session.filter,action==='shuffle');testPage();return}
 if(action==='next'){if(session.index<session.ids.length-1)session.index++;else finished=true;}
 if(action==='prev'){session.index=Math.max(0,session.index-1);finished=false;}
 if(action==='jump'){session.index=Number(button.dataset.index);finished=false;}
 revealed=false;testPage();document.querySelector('.test-surface')?.scrollIntoView({block:'start',behavior:'instant'});
});
document.querySelector('.skip-link').addEventListener('click',e=>{e.preventDefault();document.querySelector('#main')?.focus()});
window.addEventListener('hashchange',route);
window.addEventListener('keydown',e=>{if(e.key==='Escape'){const d=document.querySelector('#course-drawer');if(d){d.hidden=true;document.querySelector('.drawer-toggle')?.setAttribute('aria-expanded','false')}}});
async function boot(){try{const response=await fetch('data/index.json');if(!response.ok)throw Error('index');catalog=await response.json();await route();registerTools()}catch{app.innerHTML='<main><div class="empty-state"><h1>课程目录暂时无法加载</h1><p>请检查网络并刷新页面。</p><button class="button primary" onclick="location.reload()">刷新</button></div></main>'}}
function registerTools(){const context=document.modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();const tools=[{name:'list_courses',description:'List available BUPT courses with IDs and chapter/question counts.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>catalog.map(({id,name,chapters,questions})=>({id,name,chapters,questions}))},{name:'open_course',description:'Open a course in reading or self-test mode. Self-test answers remain hidden.',inputSchema:{type:'object',properties:{courseId:{type:'string'},mode:{type:'string',enum:['learn','test']}},required:['courseId','mode'],additionalProperties:false},annotations:{readOnlyHint:false},execute:async input=>{if(!input||!catalog.some(c=>c.id===input.courseId)||!['learn','test'].includes(input.mode))throw Error('Invalid course or mode');history.pushState(null,'',`#/course/${input.courseId}/${input.mode}`);await route();return {courseId:course.id,mode,answerVisible:revealed}}}];for(const tool of tools)try{Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{})}catch{}window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true})}
boot();
