// Public messages live in D1. Only drafts and an anonymous ownership key stay in this browser.
export function createForum({render,getCourses,icon}) {
 const escape=s=>String(s??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
 const typeNames={question:'Question','notes-request':'Notes request',discussion:'Discussion'};
 let token='',nickname='',generation=0,currentHash='',lastDetail=null;
 const drafts=new Map();
 try{token=localStorage.getItem('bupt-forum-key')||'';nickname=localStorage.getItem('bupt-forum-name')||'';}catch{}
 if(!/^[a-f0-9]{64}$/.test(token)){token=Array.from(crypto.getRandomValues(new Uint8Array(32)),b=>b.toString(16).padStart(2,'0')).join('');try{localStorage.setItem('bupt-forum-key',token);}catch{}}
 const courseName=id=>getCourses().find(c=>c.id===id)?.name||'General discussion';
 const date=value=>new Intl.DateTimeFormat('en-GB',{day:'numeric',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(value));
 const time=value=>`<time datetime="${new Date(value).toISOString()}">${date(value)}</time>`;
 const avatar=name=>`<span class="forum-avatar" aria-hidden="true">${escape(Array.from(name||'Anonymous').slice(0,2).join('').toUpperCase())}</span>`;
 function safeText(value){let result='',offset=0;for(const match of String(value).matchAll(/https?:\/\/[^\s<>"']+/g)){let link=match[0].replace(/[.,;!?，。；！)]+$/,'');result+=escape(value.slice(offset,match.index));try{const u=new URL(link);result+=`<a href="${escape(u.href)}" target="_blank" rel="noopener noreferrer ugc nofollow">${escape(link)}</a>`;}catch{result+=escape(link);}offset=match.index+link.length;}return result+escape(value.slice(offset));}
 const queryString=values=>new URLSearchParams(Object.entries(values).filter(([,v])=>v!==''&&v!=null)).toString();
 const listLink=values=>'#/forum'+(queryString(values)?'?'+queryString(values):'');
 const options=(selected,all=false)=>`${all?'<option value="">All modules</option>':''}<option value="general" ${selected==='general'?'selected':''}>General discussion</option>${getCourses().map(c=>`<option value="${c.id}" ${c.id===selected?'selected':''}>${escape(c.name)}</option>`).join('')}`;
 const kinds=selected=>Object.entries(typeNames).map(([key,label])=>`<option value="${key}" ${selected===key?'selected':''}>${label}</option>`).join('');
 const heading=()=>`<div class="forum-heading"><h1>${icon('forum')}Student forum</h1><span class="forum-open">No account required</span></div>`;
 const intro=`<div class="forum-intro"><p>Ask a course question, request missing notes or help another student.</p><p>Anyone can read and reply. Posts are public; use a nickname and leave out private details.</p></div>`;
 function show(content){render(heading()+content);}
 async function api(path,options={}){const response=await fetch('/api/forum/'+path,{...options,headers:{'X-Forum-Token':token,...(options.body?{'Content-Type':'application/json'}:{}),...options.headers}});let data;try{data=await response.json();}catch{throw Error('The forum could not load. Please try again.');}if(!response.ok){const error=Error(data.error||'The forum could not load. Please try again.');error.status=response.status;throw error;}return data;}
 function readDraft(key,defaults){if(drafts.has(key))return drafts.get(key);let draft;try{draft=JSON.parse(sessionStorage.getItem('bupt-forum-draft:'+key));}catch{}draft={id:crypto.randomUUID(),author:nickname,...defaults,...draft};drafts.set(key,draft);return draft;}
 function remember(key,data){drafts.set(key,data);try{sessionStorage.setItem('bupt-forum-draft:'+key,JSON.stringify(data));}catch{}}
 function clearDraft(key){drafts.delete(key);try{sessionStorage.removeItem('bupt-forum-draft:'+key);}catch{}}
 function form(key,defaults={},reply=false){const d=readDraft(key,defaults);return `<form class="forum-composer" data-forum-compose="${key}" data-id="${d.id}" ${reply?'data-reply="true"':''}>
 <h2>${reply?'Write a reply':'Add discussion topic'}</h2>
 <div class="forum-form-row"><label>Display name <span class="muted">(optional)</span><input name="author" maxlength="40" autocomplete="nickname" placeholder="Anonymous" value="${escape(d.author)}"></label>${!reply?`<label>Course<select name="course" required>${options(d.course||'general')}</select></label><label>Type<select name="kind">${kinds(d.kind||'question')}</select></label>`:''}</div>
 ${!reply?`<label>Subject<input name="subject" required maxlength="160" value="${escape(d.subject||'')}" placeholder="What would you like to ask or find?"></label>`:''}
 <label>${reply?'Message':'Message'}<textarea name="message" required maxlength="10000" rows="7" placeholder="Write in English or Chinese. You can include a link to your notes.">${escape(d.message||'')}</textarea></label>
 <label class="forum-honeypot" aria-hidden="true">Leave this empty<input name="website" tabindex="-1" autocomplete="off"></label>
 <p class="forum-form-hint">Your message and display name will be visible to everyone. You can remove your own posts from this browser.</p>
 <p class="forum-feedback" role="alert" hidden></p><div class="forum-form-actions"><button class="button forum-submit" type="submit">${reply?'Post reply':'Post to forum'}</button>${!reply?`<a class="button secondary" href="${listLink({course:d.course==='general'?'':d.course})}">Cancel</a>`:''}<span class="forum-draft-status" role="status"></span></div></form>`;}
 async function list(params,version){const course=params.get('course')||'',kind=params.get('kind')||'',q=params.get('q')||'',page=Number(params.get('page')||0);
  show(`<section class="forum-surface">${intro}<div class="forum-toolbar"><form id="forum-search"><label class="visually-hidden" for="forum-query">Search forums</label><input id="forum-query" name="q" type="search" maxlength="120" placeholder="Search forums" value="${escape(q)}"><button type="submit" aria-label="Search forums">${icon('search')}</button></form><a class="button forum-submit" href="#/forum/new${course?'?course='+encodeURIComponent(course):''}">Add discussion topic</a><button class="text-button" data-forum-action="refresh">Refresh</button></div>
  <div class="forum-filters"><label>Course<select id="forum-course">${options(course,true)}</select></label><label>Type<select id="forum-kind"><option value="">All discussions</option>${kinds(kind)}</select></label></div><div id="forum-list" role="status"><p class="forum-loading">Loading discussions…</p></div></section>`);
  document.querySelector('#forum-search').addEventListener('submit',e=>{e.preventDefault();location.hash=listLink({course,kind,q:new FormData(e.currentTarget).get('q')});});
  for(const [id,key] of [['forum-course','course'],['forum-kind','kind']])document.getElementById(id).addEventListener('change',e=>{location.hash=listLink({course,kind,q,[key]:e.target.value});});
  const data=await api('threads?'+queryString({course,kind,q,page}));if(version!==generation)return;
  document.querySelector('#forum-list').innerHTML=data.threads.length?`<table class="forum-table"><thead><tr><th>Discussion</th><th>Started by</th><th>Last post</th><th class="forum-count">Replies</th></tr></thead><tbody>${data.threads.map(t=>`<tr><td><a class="forum-subject" href="#/forum/thread/${t.id}">${escape(t.subject)}</a><div class="forum-topic-meta"><span class="forum-kind">${typeNames[t.kind]}</span><a href="${listLink({course:t.course})}">${escape(courseName(t.course))}</a></div></td><td data-label="Started by"><div class="forum-person">${avatar(t.author)}<div>${escape(t.author)}${time(t.created_at)}</div></div></td><td data-label="Last post"><div class="forum-person"><div>${escape(t.last_author)}${time(t.updated_at)}</div></div></td><td class="forum-count" data-label="Replies"><a href="#/forum/thread/${t.id}">${t.replies}</a></td></tr>`).join('')}</tbody></table>`:`<div class="forum-empty"><h2>${q||kind?'No matching discussions':'No discussions yet'}</h2><p>${q||kind?'Try another search or filter.':'Be the first to ask a question or request some notes.'}</p></div>`;
  document.querySelector('#forum-list').insertAdjacentHTML('beforeend',`<nav class="forum-pagination" aria-label="Discussion pages">${page>0?`<a class="button secondary" href="${listLink({course,kind,q,page:page-1})}">Previous page</a>`:'<span></span>'}<span>Page ${page+1}</span>${data.hasMore?`<a class="button secondary" href="${listLink({course,kind,q,page:page+1})}">Next page</a>`:'<span></span>'}</nav>`);
 }
 function post(row,original=false){return `<article class="forum-post ${original?'forum-original':''}"><header>${avatar(row.author)}<div><strong>${escape(row.author)}</strong>${time(row.created_at)}</div>${row.canDelete?`<button class="text-button forum-delete" data-forum-action="delete" data-type="${original?'threads':'replies'}" data-id="${row.id}">Remove my post</button>`:''}</header><div class="forum-message">${row.deleted?'<p class="muted">This message has been removed by its author.</p>':safeText(row.message)}</div></article>`;}
 async function detail(id,params,version){show('<section class="forum-surface"><p class="forum-loading">Loading discussion…</p></section>');const data=await api('threads/'+encodeURIComponent(id)+'?'+queryString({page:params.get('page')||0}));if(version!==generation)return;lastDetail=data;const t=data.thread;
  show(`<section class="forum-surface"><a class="forum-back" href="${listLink({course:t.course})}">Back to discussions</a><div class="forum-topic-heading"><span class="forum-kind">${typeNames[t.kind]}</span><a href="${listLink({course:t.course})}">${escape(courseName(t.course))}</a><h2>${escape(t.subject)}</h2></div>${post(t,true)}<h2 class="forum-replies-heading">Replies</h2>${data.replies.length?data.replies.map(r=>post(r)).join(''):'<p class="forum-no-replies">No replies yet. Share what you know.</p>'}<nav class="forum-pagination" aria-label="Reply pages">${data.page?`<a class="button secondary" href="#/forum/thread/${t.id}?page=${data.page-1}">Previous replies</a>`:'<span></span>'}<span>Page ${data.page+1}</span>${data.hasMore?`<a class="button secondary" href="#/forum/thread/${t.id}?page=${data.page+1}">Next replies</a>`:'<span></span>'}</nav>${t.deleted?'<p class="forum-intro">This discussion is closed because its opening post was removed.</p>':form('reply-'+t.id,{},true)}</section>`);
 }
 function bindComposer(){const formEl=document.querySelector('[data-forum-compose]');if(!formEl)return;const key=formEl.dataset.forumCompose;
  const capture=()=>{const d={...Object.fromEntries(new FormData(formEl)),id:formEl.dataset.id};delete d.website;remember(key,d);};formEl.addEventListener('input',capture);formEl.addEventListener('change',capture);
  formEl.addEventListener('submit',async e=>{e.preventDefault();const button=formEl.querySelector('[type=submit]'),feedback=formEl.querySelector('.forum-feedback');if(button.disabled)return;capture();const payload={...Object.fromEntries(new FormData(formEl)),id:formEl.dataset.id};const startGeneration=generation,submittedDraft=JSON.stringify(drafts.get(key));button.disabled=true;button.textContent='Posting…';feedback.hidden=true;
   try{const reply=formEl.dataset.reply;const result=await api(reply?'threads/'+key.slice(6)+'/replies':'threads',{method:'POST',body:JSON.stringify(payload)});if(JSON.stringify(drafts.get(key))===submittedDraft)clearDraft(key);nickname=payload.author;try{localStorage.setItem('bupt-forum-name',nickname);}catch{}if(startGeneration!==generation)return;
    if(reply){const target=`#/forum/thread/${result.threadId}${result.replyPage?'?page='+result.replyPage:''}`;history.replaceState(null,'',target);await route(target);document.querySelector('.forum-replies-heading')?.scrollIntoView({block:'start'});}else location.hash=`#/forum/thread/${result.threadId}`;
   }catch(error){feedback.textContent=error.message;feedback.hidden=false;if(error.status===409){const restart=document.createElement('button');restart.type='button';restart.className='button secondary';restart.textContent='Start a separate submission';restart.onclick=()=>{formEl.dataset.id=crypto.randomUUID();capture();feedback.textContent='A new submission is ready. Check your message and post it again.';};feedback.append(document.createElement('br'),restart);}}finally{button.disabled=false;button.textContent=formEl.dataset.reply?'Post reply':'Post to forum';}
  });
 }
 async function remove(button){const area=button.closest('.forum-post');if(area.querySelector('.forum-remove-confirm'))return;const box=document.createElement('div');box.className='forum-remove-confirm';box.innerHTML='<p>Remove your message? Other students’ replies will remain.</p><button class="button forum-submit" data-remove-confirm>Remove message</button> <button class="button secondary" data-remove-cancel>Keep message</button><p role="alert"></p>';area.append(box);box.querySelector('[data-remove-cancel]').onclick=()=>box.remove();box.querySelector('[data-remove-confirm]').onclick=async e=>{e.target.disabled=true;const startGeneration=generation,startHash=currentHash;try{await api(`${button.dataset.type}/${button.dataset.id}`,{method:'DELETE'});if(generation===startGeneration&&currentHash===startHash)await route(startHash,{scroll:false});}catch(error){box.querySelector('[role=alert]').textContent=error.message;e.target.disabled=false;}};box.querySelector('button').focus();}
 async function route(hash,{scroll=true}={}){if(scroll)window.scrollTo({top:0,behavior:'instant'});currentHash=hash;const version=++generation;const [path,query='']=hash.replace(/^#\/?/,'').split('?');const parts=path.split('/');const params=new URLSearchParams(query);
  try{if(parts[1]==='new'){show(`<section class="forum-surface"><a class="forum-back" href="${listLink({course:params.get('course')||''})}">Back to discussions</a>${form('new',{course:params.get('course')||'general',kind:'question'})}</section>`);}else if(parts[1]==='thread'&&parts[2])await detail(parts[2],params,version);else await list(params,version);if(version===generation)bindComposer();}
  catch(error){if(version!==generation)return;const container=document.querySelector('#forum-list');const html=`<div class="forum-error" role="alert"><h2>Forum unavailable</h2><p>${escape(error.message)}</p><button class="button secondary" data-forum-action="refresh">Try again</button></div>`;if(container)container.innerHTML=html;else show(`<section class="forum-surface">${html}</section>`);}
 }
 document.addEventListener('click',e=>{const button=e.target.closest('[data-forum-action]');if(!button)return;if(button.dataset.forumAction==='refresh')route(currentHash,{scroll:false});if(button.dataset.forumAction==='delete')remove(button);});
 return {route,cancel(){generation++;},safeText};
}
